### ISSUE TITLE
Add on / off switch to case 

### ISSUE THREAD

**Issue by fluffy** [Quicr/hactar#28]

**Comment by BrettRegnier** [comment]
Could these be a good candidate for the switch?
https://www.aliexpress.com/item/4001207529493.html?spm=a2g0o.order_list.order_list_main.41.23e41802mUHuyH

**Comment by fluffy** [comment]
I think we would be better off to get a switch we could source from JLCPCB or a place like digikey. We need to figure out how it mounts in the case and then figure out if goes on the PCB, or if it is seperate with wires that go to a connector on the PCB.

**Comment by BrettRegnier** [comment]
Added to EV11 https://github.com/Quicr/hactar/tree/ev11
