### ISSUE TITLE
Workweek exit test

### ISSUE THREAD

**Issue by shamim-pirzada** [Quicr/hactar#69]
Two Hactar systems exchange MLS messages with each other via a UDP relay.
UX experience:
Login to hactar device
Connect to Wifi
Join a preconfigured room/space
Send text message (verify received by other device)
Receive text message (send by other device)

Underlying message exchange (ignoring OKs)
Publish intent
subscribe
key exchange
welcome
message send

**Comment by BrettRegnier** [comment]
Closing as this was completed at Calgary offsite.
