### ISSUE TITLE
origin not set correct on PCB files 

### ISSUE THREAD

**Issue by fluffy** [Quicr/hactar#94]
Getting the huge inverted offsets on JLCPC on 10.1 - need to set origin on PCB layout

**Comment by BrettRegnier** [comment]
I'm not getting that issue, on JLCPCB it looks pristine to me... here is a screenshot from their website for Hactar 10.1 ![screenshot](https://github.com/Quicr/hactar/assets/16806796/beed1fa0-3083-4bb2-ac4a-14f9ffc783bb)

**Comment by fluffy** [comment]
Just add an origin mark in the PCB tool to the bottom left corner of the board.

**Comment by BrettRegnier** [comment]
https://github.com/Quicr/hactar/commit/a4b23601647d7e29d31fb3f6082b4056d6f6e17b
